// <auto-generated />
using System;
using ECommerce.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("ECommerce.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-000000000001"),
                            Name = "Electrónica"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-000000000002"),
                            Name = "Ropa"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-000000000003"),
                            Name = "Hogar"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-000000000004"),
                            Name = "Deportes"
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1d2e3f4-0000-0000-0000-000000000001"),
                            CategoryId = new Guid("a1b2c3d4-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Smartphone flagship de Samsung con pantalla Dynamic AMOLED 6.8\", cámara de 200MP, S Pen integrado y batería de 5000mAh. Procesador Snapdragon 8 Gen 3.",
                            Name = "Samsung Galaxy S24 Ultra",
                            Price = 1299.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = new Guid("c1d2e3f4-0000-0000-0000-000000000002"),
                            CategoryId = new Guid("a1b2c3d4-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "iPhone con chip A17 Pro, cámara principal de 48MP con zoom óptico 3x, pantalla Super Retina XDR 6.1\" y estructura de titanio. iOS 17.",
                            Name = "Apple iPhone 15 Pro",
                            Price = 1199.99m,
                            Stock = 35
                        },
                        new
                        {
                            Id = new Guid("c1d2e3f4-0000-0000-0000-000000000003"),
                            CategoryId = new Guid("a1b2c3d4-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Campera de cuero genuino vacuno, corte slim fit, cierre YKK, bolsillos interiores. Disponible en negro y marrón. Tallas S a XXL.",
                            Name = "Campera de Cuero Genuino",
                            Price = 189.99m,
                            Stock = 80
                        },
                        new
                        {
                            Id = new Guid("c1d2e3f4-0000-0000-0000-000000000004"),
                            CategoryId = new Guid("a1b2c3d4-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cafetera espresso compacta con bomba de 15 bares, vaporizador de leche ajustable, compatible con café molido y cápsulas ESE. Potencia 1300W.",
                            Name = "Cafetera Espresso De'Longhi Dedica",
                            Price = 299.99m,
                            Stock = 25
                        },
                        new
                        {
                            Id = new Guid("c1d2e3f4-0000-0000-0000-000000000005"),
                            CategoryId = new Guid("a1b2c3d4-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pelota oficial de entrenamiento Adidas, superficie termosellada para mayor durabilidad, cámara de butilo para retención de aire. Talla 5. FIFA Basic.",
                            Name = "Pelota de Fútbol Adidas Tiro League",
                            Price = 59.99m,
                            Stock = 200
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1c2d3e4-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@ecommerce.com",
                            Name = "Administrador",
                            PasswordHash = "$2a$11$ESxpO7zBLO34u7SY/U87ouBIpeJLJGcAHjOi3cDG7Oc2TmnnE/rEW",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Product", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
